import random

print('\n -- Guessing Game -- \n')

#guess = -99
#count = 0


"""
Function that validates user input
Params: user input
Return: value entered if it's type int
"""

def get_integer(message):
    while True:
        try:
            userInt = int(input(message))
            return userInt
        except ValueError:
            print('Please enter a whole number')
    return value

"""
guess_game() lopps until the user finds the number
that matches the one generated by the computer. It
also counts the number of steps the user takes to
find it.
Params: random number generated by the computer
Return: number of steps the user took to match the number
"""

def guess_game(rand_num):
    guess = -99
    count = 0

    while (guess != randnum):

        guess = int(input())

        if guess < randnum:
            print('Higher')
        elif guess > randnum:
            print('lower')
        else:
            print('Correct!!')
        count = count + 1
    #end of while loop
    return count


#Main
max_num = get_integer('Enter a high bound: ')
min_num = get_integer('Enter lower bound: ')

#Generate random number between the limits
randnum = random.randint(min_num, max_num+1)

print('Enter a number between ', min_num, ' and ', max_num, ': ')

steps = guess_game(randnum)

print('You took ' + str(steps) + ' steps.')